# in addition, more rabbitmq config info shall be configured by Class  com.zhousheng.rabbitmqmessagesender.rabbitmqConfig.RabbitmqConfig
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: lily
    password: lily
    virtual-host: testhostlily

server:
  port: 9014
